// Generated by VN Studio (scripts/esbuild.sitebuilder.mjs). Do not edit.
// Renders vngen/build/story.play.json into a static site. Reinstall to update.

// packages/export/src/site-cli.ts
import { mkdir, copyFile, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

// packages/export/src/site.ts
function esc(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function pageOf(sceneId) {
  const safe = sceneId.replace(/[^A-Za-z0-9._-]/g, "-").replace(/^[.-]+/, "");
  const name = safe === "" ? "scene" : safe;
  return /^(index|style)$/i.test(name) ? `${name}-scene.html` : `${name}.html`;
}
function readingOrder(playable) {
  const all = Object.keys(playable.scenes);
  const order = [];
  const seen = /* @__PURE__ */ new Set();
  const walk = (id) => {
    const scene = playable.scenes[id];
    if (seen.has(id) || !scene) return;
    seen.add(id);
    order.push(id);
    if (scene.next) walk(scene.next);
    for (const choice of scene.choices) walk(choice.goto);
  };
  if (playable.start) walk(playable.start);
  for (const id of all) walk(id);
  return order;
}
function speakerName(playable, who) {
  return playable.characters[who]?.name ?? who;
}
function renderBeat(playable, beat) {
  if (beat.type === "show") {
    if (!beat.image) return "";
    const src = `assets/${esc(beat.image.hash)}.${esc(beat.image.ext)}`;
    const alt = beat.shot ? esc(beat.shot) : "Illustration";
    return `<figure class="frame"><img src="${src}" alt="${alt}" loading="lazy"></figure>`;
  }
  if (beat.type === "say") {
    const who = esc(speakerName(playable, beat.who));
    return `<p class="say"><span class="who">${who}</span>\u201C${esc(beat.text)}\u201D</p>`;
  }
  return `<p class="narrate">${esc(beat.text)}</p>`;
}
function renderFooter(scene) {
  if (scene.choices.length > 0) {
    const items = scene.choices.map((c) => `<li><a href="${esc(pageOf(c.goto))}">${esc(c.label)}</a></li>`).join("\n      ");
    return `<nav class="choices">
    <ul>
      ${items}
    </ul>
  </nav>`;
  }
  if (scene.next) {
    return `<nav class="choices">
    <a class="continue" href="${esc(pageOf(scene.next))}">Continue \u2192</a>
  </nav>`;
  }
  return `<nav class="choices">
    <p class="ending">The End</p>
  </nav>`;
}
function document(title, body) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
${body}
</body>
</html>
`;
}
function renderScene(playable, id, scene, index, total) {
  const beats = scene.beats.map((b) => renderBeat(playable, b)).filter((html) => html !== "").join("\n    ");
  const body = `<header class="crumb">
    <a href="index.html">${esc(playable.title)}</a>
    <span class="pos">${index + 1} / ${total}</span>
  </header>
  <main class="scene">
    ${beats}
  </main>
  ${renderFooter(scene)}`;
  return document(`${playable.title} \u2014 ${id}`, body);
}
function renderIndex(playable, order) {
  const cast = Object.values(playable.characters).map((character) => {
    const portrait = character.portrait ? `<img src="assets/${esc(character.portrait.hash)}.${esc(character.portrait.ext)}" alt="${esc(character.name)}" loading="lazy">` : "";
    return `<li>${portrait}<span>${esc(character.name)}</span></li>`;
  }).join("\n      ");
  const contents = order.map((id) => `<li><a href="${esc(pageOf(id))}">${esc(id)}</a></li>`).join("\n      ");
  const start = order[0];
  const body = `<header class="title">
    <h1>${esc(playable.title)}</h1>
    ${start ? `<a class="continue" href="${esc(pageOf(start))}">Start reading \u2192</a>` : ""}
  </header>
  ${cast === "" ? "" : `<section class="cast">
    <h2>Cast</h2>
    <ul>
      ${cast}
    </ul>
  </section>`}
  <section class="contents">
    <h2>Contents</h2>
    <ol>
      ${contents}
    </ol>
  </section>`;
  return document(playable.title, body);
}
var STYLESHEET = `:root {
  color-scheme: light dark;
  --ink: #1b1b1f;
  --paper: #faf8f4;
  --muted: #6b6a72;
  --rule: rgba(0, 0, 0, 0.12);
}
@media (prefers-color-scheme: dark) {
  :root {
    --ink: #e8e6e3;
    --paper: #17171a;
    --muted: #9a98a2;
    --rule: rgba(255, 255, 255, 0.16);
  }
}
* { box-sizing: border-box; }
body {
  margin: 0 auto;
  padding: 2rem 1.25rem 5rem;
  max-width: 42rem;
  background: var(--paper);
  color: var(--ink);
  font: 1.05rem/1.7 Georgia, 'Iowan Old Style', 'Times New Roman', serif;
}
a { color: inherit; }
h1 { font-size: 2rem; line-height: 1.2; margin: 0 0 1rem; }
h2 { font-size: 1.1rem; letter-spacing: 0.08em; text-transform: uppercase; color: var(--muted); }
.crumb {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  gap: 1rem;
  padding-bottom: 0.75rem;
  border-bottom: 1px solid var(--rule);
  font-size: 0.85rem;
  color: var(--muted);
}
.crumb a { text-decoration: none; }
.pos { font-variant-numeric: tabular-nums; }
.frame { margin: 2rem 0; }
.frame img { display: block; width: 100%; height: auto; border-radius: 4px; }
.narrate { margin: 1rem 0; }
.say { margin: 1rem 0; }
.say .who {
  display: block;
  font-family: system-ui, sans-serif;
  font-size: 0.8rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--muted);
}
.choices { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid var(--rule); }
.choices ul { list-style: none; padding: 0; margin: 0; }
.choices li + li { margin-top: 0.5rem; }
.choices a { display: inline-block; padding: 0.4rem 0; }
.continue { font-family: system-ui, sans-serif; font-size: 0.95rem; text-decoration: none; }
.ending { color: var(--muted); font-style: italic; }
.cast ul { list-style: none; padding: 0; display: flex; flex-wrap: wrap; gap: 1rem; }
.cast li { width: 8rem; text-align: center; font-size: 0.9rem; }
.cast img { width: 100%; height: auto; border-radius: 4px; }
.contents ol { padding-left: 1.25rem; }
`;
function renderSite(playable) {
  const order = readingOrder(playable);
  const pages = [
    { path: "index.html", html: renderIndex(playable, order) },
    { path: "style.css", html: STYLESHEET }
  ];
  for (const [index, id] of order.entries()) {
    const scene = playable.scenes[id];
    if (!scene) continue;
    pages.push({ path: pageOf(id), html: renderScene(playable, id, scene, index, order.length) });
  }
  const assets = /* @__PURE__ */ new Map();
  for (const character of Object.values(playable.characters)) {
    if (character.portrait) assets.set(character.portrait.hash, character.portrait);
  }
  for (const id of order) {
    for (const beat of playable.scenes[id]?.beats ?? []) {
      if (beat.type === "show" && beat.image) assets.set(beat.image.hash, beat.image);
    }
  }
  return { pages, assets: [...assets.values()] };
}

// packages/export/src/site-cli.ts
var STORY_PLAY = ["vngen", "build", "story.play.json"];
var BASE_ASSETS = ["assets", "objects"];
var PROJECT_ASSETS = ["vngen", "build", "assets"];
function parse(argv) {
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i] ?? "";
    if (!arg.startsWith("--")) throw new Error(`Unexpected argument: ${arg}`);
    const body = arg.slice(2);
    const eq = body.indexOf("=");
    const key = eq === -1 ? body : body.slice(0, eq);
    if (key !== "project" && key !== "out") throw new Error(`Unknown flag: --${key}`);
    const value = eq === -1 ? argv[++i] : body.slice(eq + 1);
    if (value === void 0) throw new Error(`--${key} needs a value.`);
    flags[key] = value;
  }
  const project = resolve(flags["project"] ?? ".");
  return { project, out: resolve(flags["out"] ?? join(project, "vngen", "build", "site")) };
}
var isObject = (value) => typeof value === "object" && value !== null && !Array.isArray(value);
function asPlayable(value) {
  const bad = (what) => {
    throw new Error(`not a playable: ${what}`);
  };
  if (!isObject(value)) bad("the file is not a JSON object");
  const raw = value;
  if (typeof raw["title"] !== "string") bad("`title` is missing or not a string");
  if (!isObject(raw["characters"])) bad("`characters` is missing or not an object");
  if (!isObject(raw["scenes"])) bad("`scenes` is missing or not an object");
  for (const [id, scene] of Object.entries(raw["scenes"])) {
    if (!isObject(scene)) bad(`scene \`${id}\` is not an object`);
    const record = scene;
    if (!Array.isArray(record["beats"])) bad(`scene \`${id}\` has no \`beats\` array`);
    if (!Array.isArray(record["choices"])) bad(`scene \`${id}\` has no \`choices\` array`);
  }
  return value;
}
async function copyAsset(project, out, ref) {
  const file = `${ref.hash}.${ref.ext}`;
  const candidates = [join(project, ...BASE_ASSETS, file), join(project, ...PROJECT_ASSETS, file)];
  for (const from of candidates) {
    try {
      await copyFile(from, join(out, "assets", file));
      return true;
    } catch {
    }
  }
  process.stderr.write(`vn-site: no bytes for ${file}; skipping.
`);
  return false;
}
async function main(argv) {
  const { project, out } = parse(argv);
  const storyPlay = join(project, ...STORY_PLAY);
  let raw;
  try {
    raw = await readFile(storyPlay, "utf8");
  } catch {
    process.stderr.write(
      `vn-site: no ${storyPlay}. Run \`vngen export\` (or Export in the app) first.
`
    );
    return 1;
  }
  let playable;
  try {
    playable = asPlayable(JSON.parse(raw));
  } catch (error) {
    process.stderr.write(`vn-site: ${storyPlay} \u2014 ${error.message}
`);
    return 1;
  }
  const site = renderSite(playable);
  await mkdir(join(out, "assets"), { recursive: true });
  for (const page of site.pages) {
    const file = join(out, page.path);
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, page.html, "utf8");
  }
  let copied = 0;
  for (const ref of site.assets) if (await copyAsset(project, out, ref)) copied++;
  await writeFile(join(out, ".nojekyll"), "", "utf8");
  await writeFile(join(out, ".vn-pages"), "Published by VN Studio.\n", "utf8");
  process.stdout.write(
    `vn-site: ${site.pages.length} page(s), ${copied}/${site.assets.length} asset(s) \u2192 ${out}
`
  );
  return 0;
}
process.exitCode = await main(process.argv.slice(2));
